language: cpp
sudo: false
addons:
  apt:
    sources: &sources
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages: &deps
    - cmake
    - cmake-data
    - freeglut3-dev
    - freetype
    - libasound2-dev
    - libdevil-dev
    - libflac-dev
    - libgles2-mesa-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libogg-dev
    - libopenal-dev
    - libpulse-dev
    - libvorbis-dev
    - libvorbisenc2
    - libx11-dev
    - libxi-dev
    - libxmu-dev
    - libyaml-dev
    - xorg-dev
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MOON_MRUBY_TOOLCHAIN=gcc
        - COMPILER=g++-4.9
      before_install:
        - export CC="gcc-4.9"
        - export CXX="g++-4.9"
      addons:
        apt:
          sources:
            - *sources
          packages:
            - *deps
            - gcc-4.9
            - g++-4.9
    - os: linux
      compiler: clang
      env:
      - MOON_MRUBY_TOOLCHAIN=clang
      - COMPILER=clang++-3.7
      - LD_LIBRARY_PATH: "${TRAVIS_BUILD_DIR}/build/vendor/glfw/src"
      before_install:
      - export CC="clang-3.7"
      - export CXX="clang++-3.7"
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.7
          packages:
            - *deps
            - clang-3.7

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
      - MOON_MRUBY_TOOLCHAIN=clang
      - LD_LIBRARY_PATH: "${TRAVIS_BUILD_DIR}/build/vendor/glfw/src"

branches:
  only:
  - master
  - coverity_scan

before_install:
  - git submodule update --init --recursive --depth=1

install:
  - ./.travis/install.sh

before_script:
  - ruby --version

cache:
  directories:
  - vendor/bundle

script:
  - ./.travis/build.sh
  - ruby travis/check_libs.rb
