language: cpp
sudo: false
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - libopenal-dev
    - libdevil-dev
    - libglew-dev
    - libgles2-mesa-dev
    - freeglut3-dev
    - libx11-dev
    - libxmu-dev
    - libxi-dev
    - libyaml-dev
    - xorg-dev
    - libglu1-mesa-dev
    - cmake

  coverity_scan:
    project:
      name: "polyfox/moon"
      description: "2D game engine, with a mruby scripting system"
    notification_email: mistdragon100@gmail.com
    build_command_prepend: "echo echo"
    build_command:   "bundle exec rake build"
    branch_pattern: coverity_scan

env:
  global:
    - secure: "EI+8CM8TJ5BJJYX8TKNqUkBCdj83ZOZpZxtrxNA+6SECIqIIJ3K6KhZ3A8+P7KPx3zn/nFiAr4Wd7N9i5SX0P3mSWdxXmZeOMFwcqYLRq67LYFL4DuGVVIuAuGiydfKlG8mTZyY5p+uP3ZkwZm9ZGJ8j7OOMoLEN1xArumsKLtA="

matrix:
  include:
    - compiler: gcc
      env: MOON_MRUBY_TOOLCHAIN=gcc

    - compiler: clang
      env:
      - MOON_MRUBY_TOOLCHAIN=clang
      - LD_LIBRARY_PATH: "${TRAVIS_BUILD_DIR}/build/vendor/glfw/src"

branches:
  only:
  - master
  - coverity_scan

before_install:
  - git submodule update --init --recursive --depth=1

install:
  - gem install bundler
  - bundle install --without development --deployment  --jobs=3 --retry=3

before_script:
  - ruby --version

cache:
  directories:
  - vendor/bundle

script:
  - bundle exec rake --verbose build
  - ruby travis/check_libs.rb
