language: cpp
sudo: false
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - libopenal-dev
    - libdevil-dev
    - libglew-dev
    - libgles2-mesa-dev
    - freeglut3-dev
    - libx11-dev
    - libxmu-dev
    - libxi-dev
    - libyaml-dev
    - xorg-dev
    - libglu1-mesa-dev
    - cmake
    - cmake-data
matrix:
  include:
    - compiler: gcc
      env: MOON_MRUBY_TOOLCHAIN=gcc

    - compiler: clang
      env:
      - MOON_MRUBY_TOOLCHAIN=clang
      - LD_LIBRARY_PATH: "${TRAVIS_BUILD_DIR}/build/vendor/glfw/src"

branches:
  only:
  - master
  - coverity_scan

before_install:
  - git submodule update --init --recursive --depth=1

install:
  - gem install bundler
  - bundle install --without development --deployment  --jobs=3 --retry=3

before_script:
  - ruby --version

cache:
  directories:
  - vendor/bundle

script:
  - bundle exec rake --verbose build
  - ruby travis/check_libs.rb
